export class InternalError extends Error {
	constructor(
		public code: InternalErrorCode,
		public message: string
	) {
		super(message);
		Object.setPrototypeOf(this, InternalError.prototype);
	}
}

export default class InternalErrors {
	database(message: DatabaseErrorMessage) {
		return new InternalError(InternalErrorCode.DATABASE_ERROR, message);
	}

	validation(message: ValidationErrorMessage) {
		return new InternalError(InternalErrorCode.VALIDATION_ERROR, message);
	}

	auth(message: AuthErrorMessage) {
		return new InternalError(InternalErrorCode.AUTH_ERROR, message);
	}

	externalApi(message: ExternalApiErrorMessage) {
		return new InternalError(InternalErrorCode.EXTERNAL_API_ERROR, message);
	}

	businessLogic(message: BusinessLogicErrorMessage) {
		return new InternalError(InternalErrorCode.BUSINESS_LOGIC_ERROR, message);
	}

	spotify(message: SpotifyErrorMessage) {
		return new InternalError(InternalErrorCode.SPOTIFY_ERROR, message);
	}

	readonly discord = {
		voice(message: DiscordVoiceErrorMessage) {
			return new InternalError(InternalErrorCode.DISCORD_VOICE_ERROR, message);
		},

		api(message: DiscordApiErrorMessage) {
			return new InternalError(InternalErrorCode.DISCORD_API_ERROR, message);
		},

		permission(message: DiscordPermissionErrorMessage) {
			return new InternalError(InternalErrorCode.DISCORD_PERMISSION_ERROR, message);
		},

		guild(message: DiscordGuildErrorMessage) {
			return new InternalError(InternalErrorCode.DISCORD_GUILD_ERROR, message);
		},
	};
}

export enum InternalErrorCode {
	DATABASE_ERROR = 'DATABASE_ERROR',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	AUTH_ERROR = 'AUTH_ERROR',
	EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
	BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
	SPOTIFY_ERROR = 'SPOTIFY_ERROR',

	DISCORD_VOICE_ERROR = 'DISCORD_VOICE_ERROR',
	DISCORD_API_ERROR = 'DISCORD_API_ERROR',
	DISCORD_PERMISSION_ERROR = 'DISCORD_PERMISSION_ERROR',
	DISCORD_GUILD_ERROR = 'DISCORD_GUILD_ERROR',
}
export enum DatabaseErrorMessage {
	DEFAULT = 'DB_OPERATION_FAILED',
	CONNECTION_TIMEOUT = 'DB_CONNECTION_TIMEOUT',
	RECORD_NOT_FOUND = 'DB_RECORD_NOT_FOUND',
	DUPLICATE_KEY = 'DB_DUPLICATE_KEY',
}

export enum ValidationErrorMessage {
	DEFAULT = 'VALIDATION_FAILED',
	INVALID_SCHEMA = 'INVALID_DATA_SCHEMA',
	TYPE_MISMATCH = 'DATA_TYPE_MISMATCH',
}

export enum AuthErrorMessage {
	DEFAULT = 'INTERNAL_AUTH_FAILED',
	TOKEN_SIGNING_FAILED = 'TOKEN_SIGNING_FAILED',
	CRYPTO_ERROR = 'PASSWORD_HASHING_FAILED',
}

export enum ExternalApiErrorMessage {
	DEFAULT = 'EXTERNAL_SERVICE_ERROR',
	DISCORD_TIMEOUT = 'DISCORD_SERVICE_TIMEOUT',
	SPOTIFY_UNAVAILABLE = 'SPOTIFY_SERVICE_UNAVAILABLE',
}

export enum BusinessLogicErrorMessage {
	DEFAULT = 'BUSINESS_RULE_VIOLATION',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
	EMPTY_CONFIGURATION = 'EMPTY_CONFIGURATION',
	NO_AVAILABLE_OPTIONS = 'NO_AVAILABLE_OPTIONS',
}

export enum SpotifyErrorMessage {
	DEFAULT = 'SPOTIFY_ERROR',
	INVALID_PLAYLIST = 'INVALID_PLAYLIST',
	PLAYLIST_NOT_FOUND = 'PLAYLIST_NOT_FOUND',
	PLAYLIST_EMPTY = 'PLAYLIST_EMPTY',
	INVALID_TRACK = 'INVALID_TRACK',
	TRACK_NOT_FOUND = 'TRACK_NOT_FOUND',
	TRACK_WITHOUT_ID = 'TRACK_WITHOUT_ID',
	API_ERROR = 'SPOTIFY_API_ERROR',
	RATE_LIMITED = 'SPOTIFY_RATE_LIMITED',
	TOKEN_EXPIRED = 'SPOTIFY_TOKEN_EXPIRED',
	INVALID_TOKEN = 'SPOTIFY_INVALID_TOKEN',
	INVALID_RESPONSE = 'SPOTIFY_INVALID_RESPONSE',
}
export enum DiscordApiErrorMessage {
	DEFAULT = 'DISCORD_API_ERROR',
	TIMEOUT = 'DISCORD_API_TIMEOUT',
	RATE_LIMITED = 'DISCORD_RATE_LIMITED',
	INVALID_RESPONSE = 'DISCORD_INVALID_RESPONSE',
	UNKNOWN_ERROR = 'DISCORD_UNKNOWN_ERROR',
}

export enum DiscordPermissionErrorMessage {
	DEFAULT = 'DISCORD_PERMISSION_DENIED',
	MISSING_MANAGE_GUILD = 'DISCORD_MISSING_MANAGE_GUILD_PERMISSION',
	MISSING_MANAGE_CHANNELS = 'DISCORD_MISSING_MANAGE_CHANNELS_PERMISSION',
	MISSING_CONNECT = 'DISCORD_MISSING_CONNECT_PERMISSION',
	MISSING_SPEAK = 'DISCORD_MISSING_SPEAK_PERMISSION',
	MISSING_SEND_MESSAGES = 'DISCORD_MISSING_SEND_MESSAGES_PERMISSION',
	MISSING_ADMIN = 'DISCORD_MISSING_ADMIN_PERMISSION',
}

export enum DiscordGuildErrorMessage {
	DEFAULT = 'DISCORD_GUILD_ERROR',
	GUILD_NOT_FOUND = 'DISCORD_GUILD_NOT_FOUND',
	BOT_NOT_IN_GUILD = 'DISCORD_BOT_NOT_IN_GUILD',
	OWNER_ONLY_ACTION = 'DISCORD_OWNER_ONLY_ACTION',
	INVALID_GUILD_STATE = 'DISCORD_INVALID_GUILD_STATE',
}

export enum DiscordVoiceErrorMessage {
	DEFAULT = 'VOICE_ERROR',
	INVALID_CHANNEL_TYPE = 'VOICE_INVALID_CHANNEL_TYPE',
	CONNECTION_TIMEOUT = 'VOICE_CONNECTION_TIMEOUT',
	RECONNECT_FAILED = 'VOICE_RECONNECT_FAILED',
	MAX_RECONNECT_ATTEMPTS_REACHED = 'VOICE_MAX_RECONNECT_ATTEMPTS_REACHED',
	CHANNEL_NOT_FOUND = 'VOICE_CHANNEL_NOT_FOUND',
	NOT_CONNECTED = 'VOICE_NOT_CONNECTED',
	ALREADY_CONNECTED = 'VOICE_ALREADY_CONNECTED',
}
