packages:
  - 'apps/*'
  - 'packages/*'
  - 'types'
  - 'base'
  - 'shared/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  argon2: true
  bcrypt: true
  esbuild: true
  prisma: true
