<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <ProjectReference Include="../../../Packages/Db/Auth/AuthDb.csproj"/>
        <ProjectReference Include="../../../Packages/Libs/Libs.csproj"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12"/>
    </ItemGroup>
</Project>
