<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <!-- namespaces -->
        <_CompanyPrefix>zed31rus</_CompanyPrefix>

        <_RelativeProjectPath>$([MSBuild]::MakeRelative($(MSBuildThisFileDirectory), $(MSBuildProjectDirectory)))</_RelativeProjectPath>

        <_SanitizedPath>$(_RelativeProjectPath.Replace('/', '.').Replace('\', '.'))</_SanitizedPath>

        <RootNamespace>$(_CompanyPrefix).$(_SanitizedPath)</RootNamespace>
        
        
    </PropertyGroup>
</Project>