<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../Packages/Libs/Libs.csproj"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12"/>
    </ItemGroup>

</Project>
